version: '3.8'

services:
  parser:
    container_name: plant_parser_app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src/plant_parser/src